---
- name: Tune for nano instance types
  ansible.builtin.set_fact:
    amimoto_memcached_enabled: false
    amimoto_redis_enabled: false
    amimoto_nginx_config_worker_processes: "1"
    amimoto_php_pm: "static"
    amimoto_php_max_children: "2"
    amimoto_php_start_servers: "1"
    amimoto_php_min_spare_servers: "1"
    amimoto_php_max_spare_servers: "4"
    amimoto_php_max_requests: "200"
    amimoto_mariadb_config_innodb_buffer_pool_size: "32M"
    amimoto_mariadb_config_query_cache_size: "32M"
    amimoto_mariadb_config_tmp_table_size: "32M"
    amimoto_mariadb_config_table_open_cache: "512"
    amimoto_mariadb_config_max_connections: "64"
    amimoto_mariadb_config_thread_cache: "64"
  when: amimoto_ec2_instance_type in ["t1.micro", "t2.nano", "t3.nano", "t3a.nano", "t4g.nano"]

- name: Tune for micro instance types
  ansible.builtin.set_fact:
    amimoto_memcached_enabled: false
    amimoto_redis_enabled: false
    amimoto_nginx_config_worker_processes: "2"
    amimoto_php_max_children: "5"
    amimoto_php_start_servers: "1"
    amimoto_php_min_spare_servers: "1"
    amimoto_php_max_spare_servers: "4"
    amimoto_php_max_requests: "200"
    amimoto_mariadb_config_innodb_buffer_pool_size: "128M"
    amimoto_mariadb_config_query_cache_size: "64M"
    amimoto_mariadb_config_tmp_table_size: "64M"
    amimoto_mariadb_config_max_connections: "128"
    amimoto_mariadb_config_thread_cache: "128"
  when: amimoto_ec2_instance_type in ["t2.micro", "t3.micro", "t3a.micro", "t4g.micro"]

- name: Tune for small instance types
  ansible.builtin.set_fact:
    amimoto_nginx_config_worker_processes: "2"
    amimoto_php_max_children: "5"
    amimoto_php_start_servers: "1"
    amimoto_php_min_spare_servers: "1"
    amimoto_php_max_spare_servers: "4"
    amimoto_php_max_requests: "200"
    amimoto_mariadb_config_innodb_buffer_pool_size: "128M"
    amimoto_mariadb_config_query_cache_size: "128M"
    amimoto_mariadb_config_tmp_table_size: "128M"
    amimoto_mariadb_config_max_connections: "128"
    amimoto_mariadb_config_thread_cache: "128"
  when: amimoto_ec2_instance_type in ["t2.small", "t3.small", "t3a.small", "t4g.small", "m1.small"]

- name: Tune for medium instance types
  ansible.builtin.set_fact:
    amimoto_nginx_config_worker_processes: "2"
    amimoto_php_max_children: "20"
    amimoto_php_start_servers: "4"
    amimoto_php_min_spare_servers: "4"
    amimoto_php_max_spare_servers: "16"
    amimoto_php_max_requests: "200"
    amimoto_mariadb_config_innodb_buffer_pool_size: "256M"
    amimoto_mariadb_config_query_cache_size: "256M"
    amimoto_mariadb_config_tmp_table_size: "256M"
    amimoto_mariadb_config_max_connections: "256"
    amimoto_mariadb_config_thread_cache: "256"
  when: amimoto_ec2_instance_type in ["t2.medium", "t3.medium", "t3a.medium", "t4g.medium", "m1.medium", "m3.medium", "m7a.medium", "m7g.medium", "c7g.medium"]

- name: Tune for large instance types
  ansible.builtin.set_fact:
    amimoto_nginx_config_worker_processes: "2"
    amimoto_php_max_children: "20"
    amimoto_php_start_servers: "4"
    amimoto_php_min_spare_servers: "4"
    amimoto_php_max_spare_servers: "16"
    amimoto_php_max_requests: "200"
    amimoto_mariadb_config_innodb_buffer_pool_size: "256M"
    amimoto_mariadb_config_query_cache_size: "256M"
    amimoto_mariadb_config_tmp_table_size: "256M"
    amimoto_mariadb_config_max_connections: "256"
    amimoto_mariadb_config_thread_cache: "256"
  when: amimoto_ec2_instance_type in ["m1.large", "m3.large", "m4.large", "m5.large", "m5a.large", "m5ad.large", "m5d.large", "m5dn.large", "m5n.large", "m5zn.large", "m6i.large", "m6id.large", "m6in.large", "m6idn.large", "m6g.large", "m7a.large", "m7g.large", "m7i-flex.large", "m7i.large", "m8g.large", "c6g.large", "c7g.large", "c8g.large", "t2.large", "t3.large", "t3a.large", "t4g.large"]

- name: Tune for xlarge instance types
  ansible.builtin.set_fact:
    amimoto_nginx_config_worker_processes: "4"
    amimoto_php_max_children: "35"
    amimoto_php_start_servers: "10"
    amimoto_php_min_spare_servers: "10"
    amimoto_php_max_spare_servers: "25"
    amimoto_php_max_requests: "200"
    amimoto_mariadb_config_innodb_buffer_pool_size: "512M"
    amimoto_mariadb_config_query_cache_size: "512M"
    amimoto_mariadb_config_tmp_table_size: "512M"
    amimoto_mariadb_config_max_connections: "256"
    amimoto_mariadb_config_thread_cache: "256"
  when: amimoto_ec2_instance_type in ["m1.xlarge", "m2.xlarge", "m3.xlarge", "m4.xlarge", "m5.xlarge", "m5a.xlarge", "m5ad.xlarge", "m5d.xlarge", "m5dn.xlarge", "m5n.xlarge", "m5zn.xlarge", "m6i.xlarge", "m6id.xlarge", "m6in.xlarge", "m6idn.xlarge", "m7a.xlarge", "m7i-flex.xlarge", "m7i.xlarge", "t2.xlarge", "t3.xlarge", "t3a.xlarge"]

- name: Tune for 2xlarge instance types
  ansible.builtin.set_fact:
    amimoto_nginx_config_worker_processes: "8"
    amimoto_php_max_children: "35"
    amimoto_php_start_servers: "10"
    amimoto_php_min_spare_servers: "10"
    amimoto_php_max_spare_servers: "25"
    amimoto_php_max_requests: "200"
    amimoto_mariadb_config_innodb_buffer_pool_size: "512M"
    amimoto_mariadb_config_query_cache_size: "512M"
    amimoto_mariadb_config_tmp_table_size: "512M"
    amimoto_mariadb_config_max_connections: "256"
    amimoto_mariadb_config_thread_cache: "256"
  when: amimoto_ec2_instance_type in ["t2.2xlarge", "t3.2xlarge", "t3a.2xlarge"]
